apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: html-openshift-app-build
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/arlindlind/Modul-210.git'
      ref: main
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'php:7.0'
        namespace: openshift
  output:
    to:
      kind: ImageStreamTag
      name: 'html-openshift-app:latest'
