FROM nginx:alpine

COPY Web /usr/share/nginx/html


# docker build -t modul-210-3-2 .
# docker run --name Modul210-3-2 -d  modul-210-3-2

# docker run --name Modul210-3-2 -d -p 8080:80 modul-210-3-2


